# Generated by Django 6.0.7 on 2026-08-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='titulo',
            field=models.TextField(default='Sin titulo'),
            preserve_default=False,
        ),
    ]
