# Generated by Django 6.0.7 on 2026-09-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_nota_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='titulo',
            field=models.TextField(default='Sin titulo'),
        ),
    ]
