# Generated by Django 6.0.7 on 2026-09-08 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_alter_nota_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='notas/')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_extra', to='notas.nota')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
