# Generated by Django 6.0.7 on 2026-08-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='plan',
            field=models.CharField(choices=[('comida', '🍽️ Comida'), ('cine', '🎬 Cine'), ('pasear', '🚶 Pasear a Pincho'), ('casa', '🏡 Plan en casa'), ('sorpresa', '🎁 Sorpresa')], default='sorpresa', max_length=20),
        ),
    ]
