# Generated by Django 6.0.7 on 2026-08-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ['orden', 'id']},
        ),
        migrations.AddField(
            model_name='mensaje',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='mensajes/'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
