# Generated by Django 6.0.7 on 2026-08-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0002_alter_mensaje_options_mensaje_imagen_mensaje_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
