# Generated by Django 6.0.7 on 2026-09-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0004_preferenciausuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='descripcion',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
