# Generated by Django 6.0.7 on 2026-09-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0005_alter_mensaje_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
