# Generated by Django 6.0.7 on 2026-09-08 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0006_alter_mensaje_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='mensajes/')),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_extra', to='mensajes.mensaje')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
