# Generated by Django 6.0.7 on 2026-09-09 17:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0007_mensajeimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciausuario',
            name='contrasena_cambiada_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
