# Generated by Django 6.0.7 on 2026-09-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0008_preferenciausuario_contrasena_cambiada_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciausuario',
            name='chocolate_visto',
            field=models.BooleanField(default=False),
        ),
    ]
